import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useLocation, useSearch } from "wouter";
import { ArrowLeft, Check, Search, UserPlus, Users, X } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Player={id:number;username:string;displayName:string;avatar:string|null;status?:"Online"|"In Game"|"Offline";friendshipId?:number;friendship?:{id:number;status:string;requesterId:number}|null};
type Request={id:number;direction:"incoming"|"outgoing";player:Player};
type GameInvite={id:number;roomId:string;gameMode:string;pointGoal:string;sender:Player};
const initials=(p:Player)=>p.displayName.slice(0,2).toUpperCase();

function PlayerRow({player,action,onProfile}:{player:Player;action?:React.ReactNode;onProfile:()=>void}) { return <div className="flex items-center gap-3 py-3"><button onClick={onProfile} className="flex items-center gap-3 min-w-0 flex-1 text-left"><Avatar><AvatarImage src={player.avatar||undefined}/><AvatarFallback>{initials(player)}</AvatarFallback></Avatar><span className="min-w-0"><span className="block font-medium truncate">{player.displayName}</span><span className="block text-sm text-muted-foreground truncate">@{player.username}</span></span></button>{player.status&&<Badge variant={player.status==="Online"?"default":"secondary"}>{player.status}</Badge>}{action}</div> }

export default function PlayWithFriends(){
 const [,navigate]=useLocation();const searchString=useSearch();const defaults=new URLSearchParams(searchString);const {toast}=useToast();
 const [searchOpen,setSearchOpen]=useState(false),[q,setQ]=useState(""),[debounced,setDebounced]=useState("");const [profile,setProfile]=useState<Player|null>(null),[invitee,setInvitee]=useState<Player|null>(null);const [mode,setMode]=useState(defaults.get("mode")||"ace_high"),[points,setPoints]=useState(defaults.get("points")||"300");
 useEffect(()=>{const t=setTimeout(()=>setDebounced(q.trim()),300);return()=>clearTimeout(t)},[q]);
 const friends=useQuery<{friends:Player[]}>({queryKey:["/api/friends"],refetchInterval:15000,staleTime:5000});
 const requests=useQuery<{requests:Request[];gameInvites:GameInvite[]}>({queryKey:["/api/friends/requests"],refetchInterval:10000,staleTime:3000});
 const results=useQuery<{players:Player[]}>({queryKey:[`/api/players/search?q=${encodeURIComponent(debounced)}&page=1`],enabled:debounced.length>=2,staleTime:5000});
 const refresh=()=>queryClient.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith("/api/friends")||String(q.queryKey[0]).startsWith("/api/players")});
 const mutate=useMutation({mutationFn:({method,url,data}:{method:string;url:string;data?:unknown})=>apiRequest(method,url,data),onSuccess:refresh,onError:(e:Error)=>toast({title:"Couldn't complete that action",description:e.message,variant:"destructive"})});
 const sendInvite=async()=>{if(!invitee)return;try{const res=await apiRequest("POST","/api/game-invites",{recipientIds:[invitee.id],gameMode:mode,pointGoal:points});const data=await res.json();setInvitee(null);toast({title:"Game invite sent",description:`Waiting for ${invitee.displayName} to accept.`});navigate(`/matchmaking?private=${data.room.id}&mode=${mode}&points=${points}`)}catch(e){toast({title:"Invite failed",description:(e as Error).message,variant:"destructive"})}};
 const accepted=friends.data?.friends||[],online=accepted.filter(f=>f.status!=="Offline");
 return <div className="min-h-screen bg-background"><main className="max-w-2xl mx-auto px-4 py-6 space-y-7">
  <div className="flex items-center justify-between"><Button variant="ghost" onClick={()=>navigate("/online")}><ArrowLeft className="h-4 w-4 mr-2"/>Online Play</Button><Button size="icon" variant={searchOpen?"default":"outline"} onClick={()=>setSearchOpen(!searchOpen)} aria-label="Search players"><Search className="h-4 w-4"/></Button></div>
  <div><p className="text-sm font-medium text-primary">ONLINE PLAY</p><h1 className="text-3xl font-bold">Play With Friends</h1><p className="text-muted-foreground">Invite your crew to a private House Spades table.</p></div>
  {searchOpen&&<section className="space-y-3"><Input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a player"/><Card><CardContent className="divide-y">{debounced.length<2?<p className="py-6 text-center text-sm text-muted-foreground">Enter at least 2 characters.</p>:results.data?.players.length?results.data.players.map(p=><PlayerRow key={p.id} player={p} onProfile={()=>setProfile(p)} action={p.friendship?.status==="accepted"?<Button size="sm" onClick={()=>setInvitee(p)}>Invite</Button>:p.friendship?.status==="pending"?<Button size="sm" disabled>Request Sent</Button>:<Button size="sm" variant="outline" onClick={()=>mutate.mutate({method:"POST",url:"/api/friends/request",data:{recipientId:p.id}})}><UserPlus className="h-4 w-4 mr-1"/>Add Friend</Button>}/>):<p className="py-6 text-center text-sm text-muted-foreground">No players found.</p>}</CardContent></Card></section>}
  {!!requests.data?.gameInvites.length&&<section><h2 className="text-xs font-bold tracking-widest text-muted-foreground mb-2">GAME INVITES</h2><div className="space-y-2">{requests.data.gameInvites.map(i=><Card key={i.id}><CardContent className="py-4"><p><b>{i.sender.displayName}</b> wants to play House Spades.</p><div className="flex gap-2 mt-3"><Button size="sm" onClick={async()=>{const r=await apiRequest("POST",`/api/game-invites/${i.id}/accept`,{});const d=await r.json();navigate(`/matchmaking?private=${d.lobby.id}&mode=${i.gameMode}&points=${i.pointGoal}`)}}><Check className="h-4 w-4 mr-1"/>Accept</Button><Button size="sm" variant="outline" onClick={()=>mutate.mutate({method:"POST",url:`/api/game-invites/${i.id}/decline`,data:{}})}><X className="h-4 w-4 mr-1"/>Decline</Button></div></CardContent></Card>)}</div></section>}
  <section><h2 className="text-xs font-bold tracking-widest text-muted-foreground mb-2">FRIENDS ONLINE</h2><Card><CardContent className="divide-y">{online.length?online.map(p=><PlayerRow key={p.id} player={p} onProfile={()=>setProfile(p)} action={<Button size="sm" disabled={p.status==="In Game"} onClick={()=>setInvitee(p)}>Invite</Button>}/>):<p className="py-6 text-center text-sm text-muted-foreground">No friends online right now.</p>}</CardContent></Card></section>
  <section><h2 className="text-xs font-bold tracking-widest text-muted-foreground mb-2">FRIENDS</h2><Card><CardContent className="divide-y">{accepted.length?accepted.map(p=><PlayerRow key={p.id} player={p} onProfile={()=>setProfile(p)} action={p.status!=="Offline"?<Button size="sm" disabled={p.status==="In Game"} onClick={()=>setInvitee(p)}>Invite</Button>:undefined}/>):<p className="py-6 text-center text-sm text-muted-foreground"><Users className="mx-auto h-6 w-6 mb-2"/>Search for a player to add your first friend.</p>}</CardContent></Card></section>
  <section><h2 className="text-xs font-bold tracking-widest text-muted-foreground mb-2">FRIEND REQUESTS</h2><div className="space-y-2">{requests.data?.requests.length?requests.data.requests.map(r=><Card key={r.id}><CardContent className="py-4"><p>{r.direction==="incoming"?<><b>{r.player.displayName}</b> wants to be friends.</>:<>Friend request sent to <b>{r.player.displayName}</b>.</>}</p><div className="flex gap-2 mt-3">{r.direction==="incoming"?<><Button size="sm" onClick={()=>mutate.mutate({method:"POST",url:`/api/friends/${r.id}/accept`,data:{}})}>Accept</Button><Button size="sm" variant="outline" onClick={()=>mutate.mutate({method:"POST",url:`/api/friends/${r.id}/decline`,data:{}})}>Decline</Button></>:<Button size="sm" variant="outline" onClick={()=>mutate.mutate({method:"DELETE",url:`/api/friends/${r.id}`})}>Cancel Request</Button>}</div></CardContent></Card>):<p className="text-sm text-muted-foreground">No pending requests.</p>}</div></section>
 </main>
 <Dialog open={!!profile} onOpenChange={()=>setProfile(null)}><DialogContent><DialogHeader><DialogTitle>{profile?.displayName}</DialogTitle><DialogDescription>@{profile?.username}</DialogDescription></DialogHeader>{profile&&<div className="flex items-center gap-4"><Avatar className="h-16 w-16"><AvatarImage src={profile.avatar||undefined}/><AvatarFallback>{initials(profile)}</AvatarFallback></Avatar><div><p className="font-medium">House Spades player</p>{profile.status&&<Badge variant="secondary">{profile.status}</Badge>}</div></div>}</DialogContent></Dialog>
 <Dialog open={!!invitee} onOpenChange={()=>setInvitee(null)}><DialogContent><DialogHeader><DialogTitle>Invite {invitee?.displayName}</DialogTitle><DialogDescription>Choose the existing House Spades game settings for your private room.</DialogDescription></DialogHeader><label className="space-y-2"><span className="text-sm font-medium">Game mode</span><Select value={mode} onValueChange={setMode}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ace_high">Ace High</SelectItem><SelectItem value="joker_joker_deuce_deuce">Joker Joker Deuce Deuce</SelectItem></SelectContent></Select></label><label className="space-y-2"><span className="text-sm font-medium">Point goal</span><Select value={points} onValueChange={setPoints}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="100">100</SelectItem><SelectItem value="300">300</SelectItem><SelectItem value="500">500</SelectItem></SelectContent></Select></label><Button onClick={sendInvite}>Send Game Invite</Button></DialogContent></Dialog>
 </div>
}
